spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  hibernate:
    jdbc:
      batch_size: 1000
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100000
          order_inserts: true
          order_updates: true
  data:
    mongodb:
      database: bookdb
      port: 27017
  batch:
    job:
      enabled: false
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.lesson19.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local