server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
    maximum-pool-size: 10
    minimum-idle: 5
    maximum-idle: 10
    connectionTimeout: 30000
    maximumLifetime: 1800000
  task:
    execution:
      pool:
        core-size: 80
        max-size: 160
        queue-capacity: 400
        keep-alive: 10s

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL
    show-sql: true
    open-in-view: false
  data:
    mongodb:
      database: bookdb
      port: 27017
  batch:
    job:
      enabled: true
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.lesson19.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local